name: StandardJS
on: push
jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run StandardJS
        run: yarn standard
